
local constants = {}
local rps = {}
rps.MAX_DAMAGE_PERCENT      = 90
rps.MAX_DAMAGE_TEMPERATURE  = 1200
rps.MIN_COOLANT_FILL        = 0.10
rps.MAX_WASTE_FILL          = 0.95
rps.MAX_HEATED_COOLANT_FILL = 0.95
constants.RPS_LIMITS = rps
local annunc = {}
annunc.RCSFlowLow_H2O     = -3.2
annunc.RCSFlowLow_NA      = -2.0
annunc.CoolantLevelLow    = 0.4
annunc.OpTempTolerance    = 5
annunc.ReactorHighDeltaT  = 50
annunc.FuelLevelLow       = 0.05
annunc.WasteLevelHigh     = 0.80
annunc.WaterLevelLow      = 0.4
annunc.SteamFeedMismatch  = 10
annunc.SFM_MaxSteamDT_H20 = 2.0
annunc.SFM_MinWaterDT_H20 = -3.0
annunc.SFM_MaxSteamDT_NA  = 2.0
annunc.SFM_MinWaterDT_NA  = -2.0
annunc.RadiationWarning   = 0.00001
constants.ANNUNCIATOR_LIMITS = annunc
local alarms = {}
alarms.HIGH_WASTE     = 0.85
alarms.HIGH_RADIATION = 0.00005   -- 50 uSv/h, not yet damaging but this isn't good
alarms.CHARGE_HIGH      = 1.0
alarms.CHARGE_RE_ENABLE = 0.95
alarms.FAC_HIGH_RAD     = 0.00001
constants.ALARM_LIMITS = alarms
local rs = {}
rs.ENERGY_CHARGE_LOW  = 0.05
rs.ENERGY_CHARGE_HIGH = 0.95
rs.AUX_COOL_ENABLE    = 0.85
rs.AUX_COOL_DISABLE   = 1.00
constants.RS_THRESHOLDS = rs
constants.ENERGY_MISMATCH_TOL = 0.01
constants.PU_FALLBACK_MIN_TIME_MS = 3000
constants.FLOW_STABILITY_DELAY_MS = 10000
constants.LOW_RADIATION       = 0.00001
constants.HAZARD_RADIATION    = 0.00006
constants.HIGH_RADIATION      = 0.001
constants.VERY_HIGH_RADIATION = 0.1
constants.SEVERE_RADIATION    = 8.0
constants.EXTREME_RADIATION   = 100.0
constants.WARN_RTT = 300
constants.HIGH_RTT = 500
local mek = {}
mek.STANDARD_FE_PER_MB = 80000
mek.REF_TURBINE_FLOW   = 4896000
mek.REF_TURBINE_CAP    = 108416000
mek.BASE_BOIL_TEMP          = 373.15
mek.STEAM_ENERGY_EFF        = 0.2
mek.BOILER_CASING_HEAT_CAP  = 50
mek.SODIUM_CONDUCTIVITY     = 1
mek.SODIUM_THERMAL_ENTHALPY = 5
mek.WATER_THERMAL_ENTHALPY = 10
mek.JOULES_PER_MB          = 1000000
mek.TURBINE_GAS_PER_TANK   = 64000
mek.TURBINE_DISPERSER_FLOW = 1280
mek.TURBINE_VENT_FLOW      = 32000
constants.mek = mek
return constants
